name: Unit Tests

on: [push]

jobs:
  unit_tests:
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            wxpython: https://extras.wxpython.org/wxPython4/extras/linux/gtk2/ubuntu-18.04/wxPython-4.1.0-cp37-cp37m-linux_x86_64.whl
            python: xvfb-run python3
            pip_arg: ""
          - os: ubuntu-20.04
            wxpython: https://extras.wxpython.org/wxPython4/extras/linux/gtk2/ubuntu-18.04/wxPython-4.1.0-cp37-cp37m-linux_x86_64.whl
            python: xvfb-run python3
            pip_arg: ""
          - os: macos-10.15
            wxpython: wxpython
            python: python3
            pip_arg: ""
          - os: windows-2019
            wxpython: wxpython
            python: python
            pip_arg: --user

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Pip Dependencies
      shell: bash
      run: pip install ${{ matrix.pip_arg }} coveralls nose ${{ matrix.wxpython }}
    - name: Run Tests
      shell: bash
      run: ${{ matrix.python }} setup.py nosetests
    - name: Upload Coverage Results
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: coveralls --service=gihtub
